Added DataType in SQL Column Mapping
AzureCosmosDB/data-migration-desktop-tool pull request #149
Opened 2024-10-13 17:03 UTC by HasnainAabdani

Added DataType in SQL Column Mapping class to specify data type for each column. as exiting code doesn't support datatypes other than string. this will convenient for a user to specify column type in sink settings.

2025-01-22 19:16 UTC, philnach requested changes

2025-01-22 19:16 UTC, philnach commented on Extensions/SqlServer/Cosmos.DataTransfer.SqlServerExtension/SqlServerDataSinkExtension.cs
> +                        DataColumn dbColumn = new DataColumn(columnMapping.ColumnName, Type.GetType(columnMapping.DataType));
Thank you for making this change.  It's an excellent improvement. Adding this property to ColumnMapping will break anyone with existing config files since DataType will be null by default and [Type.GetType()](https://learn.microsoft.com/dotnet/api/system.type.gettype?view=net-9.0#system-type-gettype(system-string)) will throw a null argument exception.  Perhaps the best approach is to fall back to the current default of string and suppress the exception using the alternate [GetType](https://learn.microsoft.com/dotnet/api/system.type.gettype?view=net-9.0#system-type-gettype(system-string-system-boolean)) method.

2025-01-22 19:16 UTC, philnach commented on Extensions/SqlServer/Cosmos.DataTransfer.SqlServerExtension/SqlServerDataSinkExtension.cs
> +                        DataColumn dbColumn = new DataColumn(columnMapping.ColumnName, Type.GetType(columnMapping.DataType));
Can you update the [README.md](https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/d95e66d653a7779d3447c269c2543e4c73fb2322/Extensions/SqlServer/README.md#sink) for the extension to document the new setting and include a link to the conversion table: [Map CLR parameter data](https://learn.microsoft.com/sql/relational-databases/clr-integration-database-objects-types-net-framework/mapping-clr-parameter-data?view=sql-server-ver16&redirectedfrom=MSDN&tabs=csharp)?  Based on your outcome from my previous comment you'll want to document the default behavior of if not specified System.String is default and if type isn't valid System.String is default.

2025-01-22 19:16 UTC, philnach commented on Extensions/SqlServer/Cosmos.DataTransfer.SqlServerExtension/SqlServerDataSinkExtension.cs
> +                        DataColumn dbColumn = new DataColumn(columnMapping.ColumnName, Type.GetType(columnMapping.DataType));
Can you also update the [UnitTest data file](https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/d95e66d653a7779d3447c269c2543e4c73fb2322/Extensions/SqlServer/Cosmos.DataTransfer.SqlServerExtension.UnitTests/Data/FlatFile.json) to add the column as well?

2025-01-23 17:34 UTC, HasnainAabdani commented
pushed with above mentioned changes.

2025-01-24 14:31 UTC, philnach approved these changes
Thanks for making the changes so quickly.  They look good to me.  @bowencode can you take a look?

2025-01-31 06:49 UTC, bowencode approved these changes

2025-02-10 18:54 UTC, merged